<a href="https://colab.research.google.com/github/RobertArbon/deep_art_course/blob/master/1_Data_types_and_modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming basics

This workbook will take you through some absolute basics of programming.  To run a cell press the `play` button (on the LHS) or press `shift + enter`

**RUN THE CELLS ONE BY ONE - DON'T *RUN ALL* **

# Built in data types

We need to understand the different data types that Python uses. Below are some examples of assigning different data types. 

**Exercise**
1. Create a new `code` cell (or just edit the given cell) and use `type(x)` to find out what the type of each variable is. 
2. Google search for `data type` + *the data type you discovered* + `python 3` 
3. Create a `text` cell and copy and paste a relevant sentence of paragraph that describes that data type
4. Edit the title to reflect the data type. 

## Floats (numbers with decimals)

In [9]:
# This is 'assignment'. 
# The '=' sign means place the value '0.1' in a variable called 'x'
x = 0.1
x

0.1

In [10]:
type(x)

NameError: ignored

float

https://www.digitalocean.com/community/tutorials/understanding-data-types-in-python-3

A floating-point number or a float is a real number, meaning that it can be either a rational or an irrational number. Because of this, floating-point numbers can be numbers that can contain a fractional part, such as 9.0 or -116.42. Simply speaking, for the purposes of thinking of a float in a Python program, it is a number that contains a decimal point.

## Data type 2

In [0]:
y = 1

## Data type 3

In [0]:
z = 'strix_aluco'

## Data type 4

In [0]:
talon = [1,2,3]

## Data type 5

In [0]:
beak = {'meat': 'falcon', 'fish': 'heron'}

# Arithmetic 

We need to be able to do arithmetic and to count.  This is fairly simple in python. 

**Exercise**

1. In each section (**Operation 1, Opertation 2** etc. ) below are examples of arithmetic operations. Work out what each symbol means. 
2. Note the answer (not the arithmetical answer) in text cell below and/or change the title accordingly.   

## Operation 1 (addition)

In [0]:
x = 3
y = 2
z = x + y

The '+' symbol means addition. 

## Operation 2

In [0]:
x = 10
y = 2
z = x/y

## Operation 3


In [0]:
x = 4
y = 5
z = x*y

## Operation 4

In [22]:
x = 5
y = 7
z = x-y

-2

## Operation 5 (subtle and tricky)

In [34]:
x = 5
y = 2
z = x//y

2

# Modules 
## Introduction
To extend the functionality of Python we use modules.  

Modules contain data types and functions (more on these later). 

One very import module is `numpy`.  It handles a very important type of data called an `array`.  We're going to be using these extensively. 

See here for the [numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html) tutorial. 




## How to use a module


### Simple but clunky way

This statement imports the functionality of numpy into our session

In [0]:
import numpy

to use the data type 'array' we reference it thus: 


In [27]:
my_numpy_array = numpy.array([1,2,3])
my_numpy_array

array([1, 2, 3])

### Less clunky (best way)
We can assign it to an alias:

In [0]:
import numpy as np

and reference it similarly

In [29]:
my_numpy_array = np.array([1,2,3])
my_numpy_array

array([1, 2, 3])

### Totally streamlined (but sometimes confusing)

If we just want to access one or two data types/functions etc. from a module we can just import it directly: 

In [0]:
from numpy import array

In [31]:
my_numpy_array = array([1,2,3])
my_numpy_array

array([1, 2, 3])

## Submodules
Most modules contain modules in them.  We can reference them using dots/periods '.'. 

The `numpy` module contains 

# Numpy arrays

Very useful.  They can be any dimension: 

* 1-D array: like a list/line of numbers
* 2-D array: like a square of numbers
* 3-D array: like a cube of numbers
* N-D array: like an N-dimensional hypercube of numbers (of course)

## Creating an array
There are a myriad of ways